version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  web:
    build: .
    command: bash -c "./scripts/entrypoint.sh"
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A config beat --loglevel=info --pidfile=/tmp/celerybeat.pid
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
